linters-settings:
  govet:
    check-shadowing: true
  misspell:
    locale: US

linters:
  enable-all: true
  disable:
    - maligned
    - prealloc
    - unconvert
    - lll
    - dupl
    - goconst
    - gocyclo
